// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Add.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	Add.proto

It has these top-level messages:
	Request
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Num int64 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Response struct {
	Sum int64 `protobuf:"varint,1,opt,name=sum" json:"sum,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto1.RegisterType((*Request)(nil), "Add.Request")
	proto1.RegisterType((*Response)(nil), "Add.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Add service

type AddClient interface {
	AddNumbers(ctx context.Context, opts ...grpc.CallOption) (Add_AddNumbersClient, error)
}

type addClient struct {
	cc *grpc.ClientConn
}

func NewAddClient(cc *grpc.ClientConn) AddClient {
	return &addClient{cc}
}

func (c *addClient) AddNumbers(ctx context.Context, opts ...grpc.CallOption) (Add_AddNumbersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Add_serviceDesc.Streams[0], c.cc, "/Add.Add/AddNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &addAddNumbersClient{stream}
	return x, nil
}

type Add_AddNumbersClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type addAddNumbersClient struct {
	grpc.ClientStream
}

func (x *addAddNumbersClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *addAddNumbersClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Add service

type AddServer interface {
	AddNumbers(Add_AddNumbersServer) error
}

func RegisterAddServer(s *grpc.Server, srv AddServer) {
	s.RegisterService(&_Add_serviceDesc, srv)
}

func _Add_AddNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AddServer).AddNumbers(&addAddNumbersServer{stream})
}

type Add_AddNumbersServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type addAddNumbersServer struct {
	grpc.ServerStream
}

func (x *addAddNumbersServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *addAddNumbersServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Add_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Add.Add",
	HandlerType: (*AddServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddNumbers",
			Handler:       _Add_AddNumbers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Add.proto",
}

func init() { proto1.RegisterFile("Add.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x74, 0x4c, 0x49, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x76, 0x4c, 0x49, 0x51, 0x92, 0xe6, 0x62, 0x0f, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x2b, 0xcd, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0e, 0x02, 0x31, 0x95, 0x64, 0xb8, 0x38, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x41, 0xb2, 0xc5, 0x08, 0xd9, 0xe2, 0xd2, 0x5c, 0x23, 0x33, 0x2e, 0x90, 0x09, 0x42, 0xfa,
	0x5c, 0x5c, 0x8e, 0x29, 0x29, 0x7e, 0xa5, 0xb9, 0x49, 0xa9, 0x45, 0xc5, 0x42, 0x3c, 0x7a, 0x20,
	0x0b, 0xa0, 0x46, 0x4a, 0xf1, 0x42, 0x79, 0x10, 0x33, 0x94, 0x18, 0x34, 0x18, 0x0d, 0x18, 0x9d,
	0xd8, 0xa3, 0x58, 0xc1, 0x0e, 0x48, 0x62, 0x03, 0x53, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x83, 0xf2, 0xca, 0xfc, 0x94, 0x00, 0x00, 0x00,
}
