FROM ubuntu
#COPY /home/sukumark/GRPC/Add/server.go .
 
#ADD ../../../Add/server.go .
#COPY server.go .
COPY DockerFile .
COPY ../test.txt .
RUN mkdir proto
RUN cd proto
RUN pwd
RUN ls
#ADD ../../../../interfaces/Add.proto .
#RUN cd ..
RUN bash
